var x = 10;
var y = 20.45;
var z = "sai vardhan";
var a = null;
var b;
var c = false;
var d = Symbol("Sai");
console.log(a);
console.log(b);
console.log(c);
console.log(d);
console.log(x);
console.log(y);
console.log(z);